# Generated by Django 3.1.4 on 2021-05-02 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='articles.Comment'),
        ),
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
