# Generated by Django 3.1.4 on 2021-05-19 08:00

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210513_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='text',
            field=models.TextField(),
        ),
    ]
