# Generated by Django 3.1.4 on 2021-05-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_photo',
            field=models.ImageField(default='profile_pic.png', upload_to='photos/%Y/%m/%d'),
        ),
    ]
