# Generated by Django 3.1.4 on 2021-05-14 07:56

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210513_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=users.models.CustomDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=users.models.CustomDateTimeField(auto_now=True),
        ),
    ]
